### ISSUE TITLE
auxpow tests and name tests failing (lock not held) on "bitcoind" Travis CI build

### ISSUE THREAD

**Issue by JeremyRand** [domob1812/namecore#3] opened 2015-01-06 14:18 UTC
I enabled the standard Travis CI tests (there's already a Travis CI config file in the repo), and it looks like the master branch is failing.

You can see the current build status at https://travis-ci.org/JeremyRand/namecore/builds .

If you want to enable Travis CI builds for this repo (so you don't need me to merge changes into my repo) you can do that at https://travis-ci.org ; just log in with your GitHub account and enable builds for this repo.

Here is the relevant part of the log from the "bitcoind" build in the master branch:

    Running 132 test cases...
    
    Assertion failed: lock cs_main not held in wallet.cpp:2335; locks held:
    
    unknown location(0): fatal error in "check_auxpow": signal: SIGABRT (application abort requested)
    
    test/auxpow_tests.cpp(211): last checkpoint
    
    Assertion failed: lock cs_main not held in wallet.cpp:2335; locks held:
    
    unknown location(0): fatal error in "auxpow_pow": signal: SIGABRT (application abort requested)
    
    test/auxpow_tests.cpp(354): last checkpoint
    
    Assertion failed: lock cs_main not held in main.cpp:624; locks held:
    
    unknown location(0): fatal error in "name_tx_verification": signal: SIGABRT (application abort requested)
    
    test/name_tests.cpp(305): last checkpoint
    
    Assertion failed: lock cs not held in ./txmempool.h:226; locks held:
    
    unknown location(0): fatal error in "name_mempool": signal: SIGABRT (application abort requested)
    
    test/name_tests.cpp(31): last checkpoint
    
    *** 4 failures detected in test suite "Bitcoin Test Suite"
    
    FAIL: test/test_bitcoin
    
    Traceback (most recent call last):
    
    File "./test/bitcoin-util-test.py", line 12, in <module>
    
    "bitcoin-util-test.json",buildenv)
    
    File "/home/travis/build/JeremyRand/namecore/bitcoin-x86_64-unknown-linux-gnu/src/test/bctest.py", line 51, in bctester
    
    bctest(testDir, testObj, buildenv.exeext)
    
    File "/home/travis/build/JeremyRand/namecore/bitcoin-x86_64-unknown-linux-gnu/src/test/bctest.py", line 27, in bctest
    
    proc = subprocess.Popen(execrun, stdin=stdinCfg, stdout=subprocess.PIPE, stderr=subprocess.PIPE,universal_newlines=True)
    
    File "/usr/lib/python2.7/subprocess.py", line 679, in __init__
    
    errread, errwrite)
    
    File "/usr/lib/python2.7/subprocess.py", line 1249, in _execute_child
    
    raise child_exception
    
    OSError: [Errno 2] No such file or directory
    
    FAIL: test/bitcoin-util-test.py
    
    ==================================
    
    2 of 2 tests failed
    
    Please report to info@namecoin.org
    
    ==================================
    
    make[3]: *** [check-TESTS] Error 1
    
    make[3]: Leaving directory `/home/travis/build/JeremyRand/namecore/bitcoin-x86_64-unknown-linux-gnu/src'
    
    make[2]: *** [check-am] Error 2
    
    make[2]: Leaving directory `/home/travis/build/JeremyRand/namecore/bitcoin-x86_64-unknown-linux-gnu/src'
    
    make[1]: *** [check-recursive] Error 1
    
    make[1]: Leaving directory `/home/travis/build/JeremyRand/namecore/bitcoin-x86_64-unknown-linux-gnu/src'
    
    make: *** [check-recursive] Error 1
    
    The command "if [ "$RUN_TESTS" = "true" ]; then make check; fi" exited with 2.

Full log is at https://travis-ci.org/JeremyRand/namecore/jobs/46025001

**Comment by domob1812** [comment] 2015-01-22 07:17
For me, `test/test_bitcoin` runs fine.  Do you have any idea what the difference is in the Travis CI run?  (Sorry for being ignorant as to how Travis CI works.)

**Comment by JeremyRand** [comment] 2015-01-22 07:28
@domob1812 the bitcoind test uses the following environment variables:

    HOST=x86_64-unknown-linux-gnu PACKAGES="bc" DEP_OPTS="NO_QT=1 NO_UPNP=1 DEBUG=1" RUN_TESTS=true GOAL="install" BITCOIN_CONFIG="--enable-glibc-back-compat CPPFLAGS=-DDEBUG_LOCKORDER"

The exact build script is in .travis.yml in your repo, so you can follow along with what these are doing.  If I had to guess, I'd say it's probably the NO_QT or DEBUG flags that are broken with your changes, but I'm not sure.

**Comment by domob1812** [comment] 2015-01-22 07:33
Thanks - I'll give it some tries.  I already `--enable-debug`, but I've not tried without Qt (although I don't think this changes anything for the CLI utils).  My unfounded guess is that it may be the `CPPFLAGS=-DDEBUG_LOCKORDER`, since it also mentions something related to locks.  Will try.

**Comment by JeremyRand** [comment] 2015-01-22 07:38
If you haven't done it already, I'd strongly suggest logging into travis-ci.org with your GitHub account, and enabling builds for this repo.  Then every time you push, it will automatically start a build and you'll be able to see if you've fixed it without waiting for me to do it.  (I will do this for the main repo on the "namecoin" user once this project is moved there, but for now it's probably best for you to do it on your repo.)

**Comment by JeremyRand** [comment] 2015-01-22 07:40
Also, it looks like NO_QT works fine on the ARM build, so that's probably not the issue.  As you suggest, the most profitable place to look is probably the DEBUG_LOCKORDER.

**Comment by JeremyRand** [comment] 2015-01-22 08:18
Actually, I take that back, NO_QT works on the ARM build but the ARM build doesn't run tests.  So it's still possible that NO_QT is breaking the tests (although I suspect DEBUG_LOCKORDER is more likely).

**Comment by domob1812** [comment] 2015-01-22 14:28
I can confirm that the `DEBUG_LOCKORDER` is the culprit.  I can reproduce the error now, and should hopefully be able to fix it soon.

**Comment by domob1812** [comment] 2015-01-22 15:25
Should be fixed now.  There are still Travis CI failures reported, but not related to this issue any more.  Closing.

**Closed by domob1812** 2015-01-22 15:25 UTC
